# service.name: 'ws'
# service.component: 'ws' (defined in app code)
apiVersion: apps/v1
kind: Deployment
metadata:
  # unique name for this deployment resource
  name: quickpizza-ws
  labels: &wsLabels # application name: groups all related resources
    app.k8s.io/name: quickpizza
    # component type: defines the role of this deployment
    app.kubernetes.io/component: service
    # instance id: used for service discovery and telemetry (service.name/service_name attrs)
    app.kubernetes.io/instance: ws
spec:
  replicas: 1
  selector:
    matchLabels: *wsLabels
  template:
    metadata:
      labels: *wsLabels
    spec:
      containers:
        - name: quickpizza
          image: ghcr.io/grafana/quickpizza-local:0.15.11
          ports:
            - name: http
              containerPort: 3333
          envFrom:
            - configMapRef:
                name: quickpizza-env-common
            - configMapRef:
                name: quickpizza-env
                optional: true
          env:
            - name: QUICKPIZZA_ENABLE_WS_SERVICE
              value: "1"
            - name: QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUICKPIZZA_OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/instance']
---
# Configures value for QUICKPIZZA_WS_ENDPOINT (set in kustomization.yaml)
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-ws
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ws
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
